# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0
# This is used with cargo-check-external-types to reduce the surface area of downstream crates from
# the public API. Ideally this can have a few exceptions as possible.
allowed_external_types = [
    # opentelemetry-http
    "opentelemetry_http::HttpClient",

    # opentelemetry-sdk
    "opentelemetry_sdk::logs::export::LogExporter",
    "opentelemetry_sdk::metrics::exporter::PushMetricExporter",
    "opentelemetry_sdk::metrics::Temporality",
    "opentelemetry_sdk::trace::export::SpanExporter",

    # serde (serde_core re-export used since serde 1.0.222+)
    "serde_core::de::Deserialize",
    "serde_core::ser::Serialize",

    # tonic (pre-1.0 crate)
    "tonic::metadata::map::MetadataMap",
    "tonic::service::interceptor::Interceptor",
    "tonic::transport::channel::Channel",
    "tonic::transport::channel::tls::ClientTlsConfig",
    "tonic::transport::tls::Certificate",
    "tonic::transport::tls::Identity",
]
