// This file is @generated by prost-build.
#[cfg_attr(feature = "with-schemars", derive(schemars::JsonSchema))]
#[cfg_attr(feature = "with-serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "with-serde", serde(rename_all = "camelCase"))]
#[derive(Clone, PartialEq, Eq, Hash)]
#[cfg_attr(feature = "with-prost", derive(::prost::Message))]
#[cfg_attr(not(feature = "with-prost"), derive(Debug, Default))]
pub struct TracezCounts {
    #[cfg_attr(feature = "with-prost", prost(string, tag = "1"))]
    pub spanname: ::std::string::String,
    /// \[A\]
    #[cfg_attr(feature = "with-prost", prost(uint32, repeated, tag = "2"))]
    pub latency: ::std::vec::Vec<u32>,
    #[cfg_attr(feature = "with-prost", prost(uint32, tag = "3"))]
    pub running: u32,
    #[cfg_attr(feature = "with-prost", prost(uint32, tag = "4"))]
    pub error: u32,
}
#[cfg_attr(feature = "with-schemars", derive(schemars::JsonSchema))]
#[cfg_attr(feature = "with-serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "with-serde", serde(rename_all = "camelCase"))]
#[derive(Clone, PartialEq)]
#[cfg_attr(feature = "with-prost", derive(::prost::Message))]
#[cfg_attr(not(feature = "with-prost"), derive(Debug, Default))]
pub struct LatencyData {
    #[cfg_attr(feature = "with-prost", prost(bytes = "vec", tag = "1"))]
    pub traceid: ::std::vec::Vec<u8>,
    #[cfg_attr(feature = "with-prost", prost(bytes = "vec", tag = "2"))]
    pub spanid: ::std::vec::Vec<u8>,
    #[cfg_attr(feature = "with-prost", prost(bytes = "vec", tag = "3"))]
    pub parentid: ::std::vec::Vec<u8>,
    #[cfg_attr(feature = "with-prost", prost(fixed64, tag = "4"))]
    pub starttime: u64,
    #[cfg_attr(feature = "with-prost", prost(fixed64, tag = "5"))]
    pub endtime: u64,
    /// \[1\]
    #[cfg_attr(feature = "with-prost", prost(message, repeated, tag = "6"))]
    pub attributes: ::std::vec::Vec<super::super::common::v1::KeyValue>,
    /// \[2\]
    #[cfg_attr(feature = "with-prost", prost(message, repeated, tag = "7"))]
    pub events: ::std::vec::Vec<super::super::trace::v1::span::Event>,
    /// \[3\]
    #[cfg_attr(feature = "with-prost", prost(message, repeated, tag = "8"))]
    pub links: ::std::vec::Vec<super::super::trace::v1::span::Link>,
}
#[cfg_attr(feature = "with-schemars", derive(schemars::JsonSchema))]
#[cfg_attr(feature = "with-serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "with-serde", serde(rename_all = "camelCase"))]
#[derive(Clone, PartialEq)]
#[cfg_attr(feature = "with-prost", derive(::prost::Message))]
#[cfg_attr(not(feature = "with-prost"), derive(Debug, Default))]
pub struct RunningData {
    #[cfg_attr(feature = "with-prost", prost(bytes = "vec", tag = "1"))]
    pub traceid: ::std::vec::Vec<u8>,
    #[cfg_attr(feature = "with-prost", prost(bytes = "vec", tag = "2"))]
    pub spanid: ::std::vec::Vec<u8>,
    #[cfg_attr(feature = "with-prost", prost(bytes = "vec", tag = "3"))]
    pub parentid: ::std::vec::Vec<u8>,
    #[cfg_attr(feature = "with-prost", prost(fixed64, tag = "4"))]
    pub starttime: u64,
    /// \[1\]
    #[cfg_attr(feature = "with-prost", prost(message, repeated, tag = "5"))]
    pub attributes: ::std::vec::Vec<super::super::common::v1::KeyValue>,
    /// \[2\]
    #[cfg_attr(feature = "with-prost", prost(message, repeated, tag = "6"))]
    pub events: ::std::vec::Vec<super::super::trace::v1::span::Event>,
    /// \[3\]
    #[cfg_attr(feature = "with-prost", prost(message, repeated, tag = "7"))]
    pub links: ::std::vec::Vec<super::super::trace::v1::span::Link>,
}
#[cfg_attr(feature = "with-schemars", derive(schemars::JsonSchema))]
#[cfg_attr(feature = "with-serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "with-serde", serde(rename_all = "camelCase"))]
#[derive(Clone, PartialEq)]
#[cfg_attr(feature = "with-prost", derive(::prost::Message))]
#[cfg_attr(not(feature = "with-prost"), derive(Debug, Default))]
pub struct ErrorData {
    #[cfg_attr(feature = "with-prost", prost(bytes = "vec", tag = "1"))]
    pub traceid: ::std::vec::Vec<u8>,
    #[cfg_attr(feature = "with-prost", prost(bytes = "vec", tag = "2"))]
    pub spanid: ::std::vec::Vec<u8>,
    #[cfg_attr(feature = "with-prost", prost(bytes = "vec", tag = "3"))]
    pub parentid: ::std::vec::Vec<u8>,
    #[cfg_attr(feature = "with-prost", prost(fixed64, tag = "4"))]
    pub starttime: u64,
    /// \[1\]
    #[cfg_attr(feature = "with-prost", prost(message, repeated, tag = "5"))]
    pub attributes: ::std::vec::Vec<super::super::common::v1::KeyValue>,
    /// \[2\]
    #[cfg_attr(feature = "with-prost", prost(message, repeated, tag = "6"))]
    pub events: ::std::vec::Vec<super::super::trace::v1::span::Event>,
    /// \[3\]
    #[cfg_attr(feature = "with-prost", prost(message, repeated, tag = "7"))]
    pub links: ::std::vec::Vec<super::super::trace::v1::span::Link>,
    /// \[4\]
    #[cfg_attr(feature = "with-prost", prost(message, optional, tag = "8"))]
    pub status: ::core::option::Option<super::super::trace::v1::Status>,
}
