// This file is @generated by prost-build.
/// ProcessContext represents the payload for the process context sharing mechanism.
///
/// This message is designed to be published by OpenTelemetry SDKs via a memory-mapped
/// region, allowing external readers (such as the OpenTelemetry eBPF Profiler) to
/// discover and read resource attributes from instrumented processes without requiring
/// direct integration or process activity. It is not part of OTLP and is not
/// exchanged via the OpenTelemetry Collector.
///
/// See OTEP 4719 (<https://github.com/open-telemetry/opentelemetry-specification/blob/main/oteps/profiles/4719-process-ctx.md>)
/// for details of this mechanism.
///
/// Status: \[Development\]
#[cfg_attr(feature = "with-schemars", derive(schemars::JsonSchema))]
#[cfg_attr(feature = "with-serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "with-serde", serde(rename_all = "camelCase"))]
#[cfg_attr(feature = "with-serde", serde(default))]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProcessContext {
    /// The resource for this process.
    /// If this field is not set then no resource info is known.
    #[prost(message, optional, tag = "1")]
    pub resource: ::core::option::Option<super::super::resource::v1::Resource>,
    /// Additional attributes to share with external readers that are not part of
    /// the standard Resource. \[Optional\]
    ///
    /// This field allows publishers to include supplementary key-value pairs that
    /// may be useful for external readers but are not part of the SDK's configured
    /// Resource.
    ///
    /// Consider adding any keys here to the profiles semantic conventions in
    /// <https://opentelemetry.io/docs/specs/semconv/general/profiles/>
    #[prost(message, repeated, tag = "2")]
    pub attributes: ::prost::alloc::vec::Vec<super::super::common::v1::KeyValue>,
}
