// This file is generated by rust-protobuf 2.27.1. Do not edit
// @generated

// https://github.com/rust-lang/rust-clippy/issues/702
#![allow(unknown_lints)]
#![allow(clippy::all)]

#![allow(unused_attributes)]
#![cfg_attr(rustfmt, rustfmt::skip)]

#![allow(box_pointers)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unused_imports)]
#![allow(unused_results)]
//! Generated file from `opentelemetry/proto/collector/logs/v1/logs_service.proto`

/// Generated files are compatible only with the same version
/// of protobuf runtime.
// const _PROTOBUF_VERSION_CHECK: () = ::protobuf::VERSION_2_27_1;

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub struct ExportLogsServiceRequest {
    // message fields
    pub resource_logs: ::protobuf::RepeatedField<super::logs::ResourceLogs>,
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a ExportLogsServiceRequest {
    fn default() -> &'a ExportLogsServiceRequest {
        <ExportLogsServiceRequest as ::protobuf::Message>::default_instance()
    }
}

impl ExportLogsServiceRequest {
    pub fn new() -> ExportLogsServiceRequest {
        ::std::default::Default::default()
    }

    // repeated .opentelemetry.proto.logs.v1.ResourceLogs resource_logs = 1;


    pub fn get_resource_logs(&self) -> &[super::logs::ResourceLogs] {
        &self.resource_logs
    }
    pub fn clear_resource_logs(&mut self) {
        self.resource_logs.clear();
    }

    // Param is passed by value, moved
    pub fn set_resource_logs(&mut self, v: ::protobuf::RepeatedField<super::logs::ResourceLogs>) {
        self.resource_logs = v;
    }

    // Mutable pointer to the field.
    pub fn mut_resource_logs(&mut self) -> &mut ::protobuf::RepeatedField<super::logs::ResourceLogs> {
        &mut self.resource_logs
    }

    // Take field
    pub fn take_resource_logs(&mut self) -> ::protobuf::RepeatedField<super::logs::ResourceLogs> {
        ::std::mem::replace(&mut self.resource_logs, ::protobuf::RepeatedField::new())
    }
}

impl ::protobuf::Message for ExportLogsServiceRequest {
    fn is_initialized(&self) -> bool {
        for v in &self.resource_logs {
            if !v.is_initialized() {
                return false;
            }
        };
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                1 => {
                    ::protobuf::rt::read_repeated_message_into(wire_type, is, &mut self.resource_logs)?;
                },
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        for value in &self.resource_logs {
            let len = value.compute_size();
            my_size += 1 + ::protobuf::rt::compute_raw_varint32_size(len) + len;
        };
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        for v in &self.resource_logs {
            os.write_tag(1, ::protobuf::wire_format::WireTypeLengthDelimited)?;
            os.write_raw_varint32(v.get_cached_size())?;
            v.write_to_with_cached_sizes(os)?;
        };
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ExportLogsServiceRequest {
        ExportLogsServiceRequest::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let mut fields = ::std::vec::Vec::new();
            fields.push(::protobuf::reflect::accessor::make_repeated_field_accessor::<_, ::protobuf::types::ProtobufTypeMessage<super::logs::ResourceLogs>>(
                "resource_logs",
                |m: &ExportLogsServiceRequest| { &m.resource_logs },
                |m: &mut ExportLogsServiceRequest| { &mut m.resource_logs },
            ));
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<ExportLogsServiceRequest>(
                "ExportLogsServiceRequest",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static ExportLogsServiceRequest {
        static instance: ::protobuf::rt::LazyV2<ExportLogsServiceRequest> = ::protobuf::rt::LazyV2::INIT;
        instance.get(ExportLogsServiceRequest::new)
    }
}

impl ::protobuf::Clear for ExportLogsServiceRequest {
    fn clear(&mut self) {
        self.resource_logs.clear();
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ExportLogsServiceRequest {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ExportLogsServiceRequest {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

#[derive(PartialEq,Clone,Default)]
#[cfg_attr(feature = "with-serde", derive(::serde::Serialize, ::serde::Deserialize))]
pub struct ExportLogsServiceResponse {
    // special fields
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub unknown_fields: ::protobuf::UnknownFields,
    #[cfg_attr(feature = "with-serde", serde(skip))]
    pub cached_size: ::protobuf::CachedSize,
}

impl<'a> ::std::default::Default for &'a ExportLogsServiceResponse {
    fn default() -> &'a ExportLogsServiceResponse {
        <ExportLogsServiceResponse as ::protobuf::Message>::default_instance()
    }
}

impl ExportLogsServiceResponse {
    pub fn new() -> ExportLogsServiceResponse {
        ::std::default::Default::default()
    }
}

impl ::protobuf::Message for ExportLogsServiceResponse {
    fn is_initialized(&self) -> bool {
        true
    }

    fn merge_from(&mut self, is: &mut ::protobuf::CodedInputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        while !is.eof()? {
            let (field_number, wire_type) = is.read_tag_unpack()?;
            match field_number {
                _ => {
                    ::protobuf::rt::read_unknown_or_skip_group(field_number, wire_type, is, self.mut_unknown_fields())?;
                },
            };
        }
        ::std::result::Result::Ok(())
    }

    // Compute sizes of nested messages
    #[allow(unused_variables)]
    fn compute_size(&self) -> u32 {
        let mut my_size = 0;
        my_size += ::protobuf::rt::unknown_fields_size(self.get_unknown_fields());
        self.cached_size.set(my_size);
        my_size
    }

    fn write_to_with_cached_sizes(&self, os: &mut ::protobuf::CodedOutputStream<'_>) -> ::protobuf::ProtobufResult<()> {
        os.write_unknown_fields(self.get_unknown_fields())?;
        ::std::result::Result::Ok(())
    }

    fn get_cached_size(&self) -> u32 {
        self.cached_size.get()
    }

    fn get_unknown_fields(&self) -> &::protobuf::UnknownFields {
        &self.unknown_fields
    }

    fn mut_unknown_fields(&mut self) -> &mut ::protobuf::UnknownFields {
        &mut self.unknown_fields
    }

    fn as_any(&self) -> &dyn (::std::any::Any) {
        self as &dyn (::std::any::Any)
    }
    fn as_any_mut(&mut self) -> &mut dyn (::std::any::Any) {
        self as &mut dyn (::std::any::Any)
    }
    fn into_any(self: ::std::boxed::Box<Self>) -> ::std::boxed::Box<dyn (::std::any::Any)> {
        self
    }

    fn descriptor(&self) -> &'static ::protobuf::reflect::MessageDescriptor {
        Self::descriptor_static()
    }

    fn new() -> ExportLogsServiceResponse {
        ExportLogsServiceResponse::new()
    }

    fn descriptor_static() -> &'static ::protobuf::reflect::MessageDescriptor {
        static descriptor: ::protobuf::rt::LazyV2<::protobuf::reflect::MessageDescriptor> = ::protobuf::rt::LazyV2::INIT;
        descriptor.get(|| {
            let fields = ::std::vec::Vec::new();
            ::protobuf::reflect::MessageDescriptor::new_pb_name::<ExportLogsServiceResponse>(
                "ExportLogsServiceResponse",
                fields,
                file_descriptor_proto()
            )
        })
    }

    fn default_instance() -> &'static ExportLogsServiceResponse {
        static instance: ::protobuf::rt::LazyV2<ExportLogsServiceResponse> = ::protobuf::rt::LazyV2::INIT;
        instance.get(ExportLogsServiceResponse::new)
    }
}

impl ::protobuf::Clear for ExportLogsServiceResponse {
    fn clear(&mut self) {
        self.unknown_fields.clear();
    }
}

impl ::std::fmt::Debug for ExportLogsServiceResponse {
    fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
        ::protobuf::text_format::fmt(self, f)
    }
}

impl ::protobuf::reflect::ProtobufValue for ExportLogsServiceResponse {
    fn as_ref(&self) -> ::protobuf::reflect::ReflectValueRef {
        ::protobuf::reflect::ReflectValueRef::Message(self)
    }
}

static file_descriptor_proto_data: &'static [u8] = b"\
    \n8opentelemetry/proto/collector/logs/v1/logs_service.proto\x12%opentele\
    metry.proto.collector.logs.v1\x1a&opentelemetry/proto/logs/v1/logs.proto\
    \"j\n\x18ExportLogsServiceRequest\x12N\n\rresource_logs\x18\x01\x20\x03(\
    \x0b2).opentelemetry.proto.logs.v1.ResourceLogsR\x0cresourceLogs\"\x1b\n\
    \x19ExportLogsServiceResponse2\x9d\x01\n\x0bLogsService\x12\x8d\x01\n\
    \x06Export\x12?.opentelemetry.proto.collector.logs.v1.ExportLogsServiceR\
    equest\x1a@.opentelemetry.proto.collector.logs.v1.ExportLogsServiceRespo\
    nse\"\0B\x86\x01\n(io.opentelemetry.proto.collector.logs.v1B\x10LogsServ\
    iceProtoP\x01ZFgithub.com/open-telemetry/opentelemetry-proto/gen/go/coll\
    ector/logs/v1b\x06proto3\
";

static file_descriptor_proto_lazy: ::protobuf::rt::LazyV2<::protobuf::descriptor::FileDescriptorProto> = ::protobuf::rt::LazyV2::INIT;

fn parse_descriptor_proto() -> ::protobuf::descriptor::FileDescriptorProto {
    ::protobuf::Message::parse_from_bytes(file_descriptor_proto_data).unwrap()
}

pub fn file_descriptor_proto() -> &'static ::protobuf::descriptor::FileDescriptorProto {
    file_descriptor_proto_lazy.get(|| {
        parse_descriptor_proto()
    })
}
