#![cfg_attr(docsrs, feature(doc_cfg))]
//! This crate contains generated OTLP protobuf types from the
//! [opentelemetry-proto](https://github.com/open-telemetry/opentelemetry-proto)
//! repository.
//!
//! Enable `gen-tonic-messages` to generate message types using
//! [prost](https://github.com/tokio-rs/prost), or `gen-tonic` to also include
//! [tonic](https://github.com/hyperium/tonic) gRPC client/server transport support.
//!
//!
//! # Feature flags
//! `Opentelemetry-proto` includes a set of feature flags to avoid pull in unnecessary dependencies.
//! The following is the full list of currently supported features:
//!
//! ## Signals
//! - `trace`: generate types that used in traces. Currently supports `gen-tonic`.
//! - `metrics`: generate types that used in metrics. Currently supports `gen-tonic`.
//! - `logs`: generate types that used in logs. Currently supports `gen-tonic`.
//! - `zpages`: generate types that used in zPages. Currently only tracez related types will be generated. Currently supports `gen-tonic`.
//!
//! ## Creates used to generate files
//! - `gen-tonic-messages`: generate OTLP message types using [prost](https://github.com/tokio-rs/prost).
//! - `gen-tonic`: add tonic gRPC client/server transport support on top of `gen-tonic-messages`.
//!
//! ## Misc
//! - `full`: enabled all features above.
//!
//! By default, no feature is enabled.

// proto mod contains file generated by protobuf or other build tools.
// we shouldn't manually change it. Thus skip format and lint check.
#[rustfmt::skip]
#[allow(warnings)]
#[doc(hidden)]
mod proto;

#[cfg(feature = "gen-tonic-messages")]
pub use proto::tonic;
